### ISSUE TITLE
Правки до ДЗ 25

### ISSUE THREAD

**Issue by Dexter19** [VitaliiSukhorukov/VitaliiSukhorukov.github.io#1]
Зроби декілька виправлень у своєму коді:
Передача змінної students у функцію createTable через використання шаблонних рядків в createTable не здійснюється належним чином. Очікується, що функція createTable прийматиме список студентів, але вона використовує values[0] для доступу до першого аргументу, що не є правильним.
У функції createTable не передаються властивості рядка, такі як strings[1] та strings[2], які використовуються у рядку шаблону.
І на останок використання ${students} у шаблонних рядках не дозволяє коректно відображати дані студентів в таблиці.

const students = [
    {'firstName': 'Tom', 'lastName': 'Cat', 'degree': 230},
    {'firstName': 'Nary', 'lastName': 'Ann', 'degree': 336},
    {'firstName': 'John', 'lastName': 'Doe', 'degree': 400},
    {'firstName': 'James', 'lastName': 'Bond', 'degree': 700},
];

function createTable(strings, ...values) {
    let headers = '';
    let rows = '';

    values.forEach((elem, index) => {
        if (index === 0) {
            headers = `<tr>${Object.keys(elem[0]).map(key => `<th style="background-color: blue; color: azure;">${key}</th>`).join('')}</tr>`;
        }
        rows += elem.map(item => `<tr>${Object.values(item).map(val => `<td>${val}</td>`).join('')}</tr>`).join('');
    });

    return `${strings[0]}${headers}${strings[1]}${rows}${strings[2]}`;
}

let table = createTable`<table>
   <thead>
        ${[students]}
   </thead>
   <tbody>
        ${students}
   </tbody>
</table>`;

document.body.insertAdjacentHTML('afterbegin', table);

**Comment by VitaliiSukhorukov** [comment]
- Передача змінної students у функцію createTable через використання шаблонних рядків в createTable не здійснюється належним чином. Очікується, що функція createTable прийматиме список студентів, але вона використовує values[0] для доступу до першого аргументу, що не є правильним.
 
**Виправив(видалил непотрыбний spread оператор)**

- У функції createTable не передаються властивості рядка, такі як strings[1] та strings[2], які використовуються у рядку шаблону.

**Не зовсім зрозумів помилку. Так як  createTable  приймае два параметри масів рядків strings та масів обьектів values**


- 3.І на останок використання ${students} у шаблонних рядках не дозволяє коректно відображати дані студентів в таблиці.

**Не зовсім зрозумів чому вона не дозволяє коректно відображати дані студентів в таблиці**
